#---------------------------------------------------------------------

# This file was generated by F:\Programming\Kodi Genre and Tag Manager\image2py.py

from wx.lib.embeddedimage import PyEmbeddedImage

catalog = {}
#---------------------------------------------------------------------

icon_ico = PyEmbeddedImage( 
    "iVBORw0KGgoAAAANSUhEUgAAAQAAAAEACAYAAABccqhmAAAABHNCSVQICAgIfAhkiAAACIVJ"
    "REFUeJzt3WuMXHUdx+Hf7Gy7W7bbC6W0S0tpKaFWKbaWRkQSE2pMqDSAMUHFxEQwRkJAAyZE"
    "YmKiUV+IEgVeaAIiimliNHhplYCAXAKhCBSolEtLl5bS0hvbbne33ZnjCwMp2Ia9zfxn9v88"
    "L5thzzfD9pOZ0zNnIgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAACC5UuoBtXb2det+UKlUrk69I5VyOSobbrpoxlAfv+S6dd+uVio31nJT"
    "s2gpl29+7qYLv5d6Ry21ph5Qa0VRtJfL5ampd6RSiagM8z9py/n5eo8i2lNPqLWW1AOAdAQA"
    "MiYAkDEBgIwJAGRMACBjAgAZEwDImABAxgQAMjbuLwWmMbWUSrHolMmxbP7UWDRnSsybMSlm"
    "TmmLjrZytLSUYnCwGj19g7GzZyBe29UbG7cfiKc274/te/tSTx9XBIC6WjCrIy49pys+vWRW"
    "nDh5wnEf19baEh3trdE1vT2WnjY1Llnxvz/fsrM31j27M/7y1I7Y13ukTqvHLwGgLhbP6Yyv"
    "r1wQ55554qh+zoJZHXHVZ06PKy+YH39evyPueHBr7Dl4eIxW5kcAqKnO9ta45sKFsXp515j+"
    "3ImtLfH5c+fEqmWz41f3b4k1j2+ParUY02PkwElAambpaVPj7mtWjPlf/qOd0FaOa1edEbd+"
    "9aNxUufEmh1nvBIAamL18q649YqlMXNKW12Ot2z+tLjzqnNiUdfkuhxvvBAAxtxl582NGy9d"
    "FOWW+t5wakbnxLjtyqWx5NQpdT1uMxMAxtTq5V3xrVVnJDt+R1tr3PyVs2PhbK8EhkIAGDNL"
    "T5saN1x8ZuoZ0dHeGj+5/KyYOsk57g8iAIyJzvbW+P5lH677y/7j6ZreHt/53Iei1BhzGpYA"
    "MCauWXVG3U74DdWnFp8UK886OfWMhiYAjNriOZ2x+mOzU884pmsvXBhtE8qpZzQsAWDUvnbB"
    "/NQTjmvmlLa4ZEXtrkNodgLAqCw4uSPOWzTk7x1J4gufmBstTgYckwAwKhc16Ev/o3VNb4/l"
    "p09LPaMhCQAjVipFrDxrZuoZQ7LyI82xs94EgBGbN+OEmD2tOb49a7SfQhyvBIARWzKveS65"
    "nT2t3YeFjkEAGLGFs5rrcttm21sPAsCIdU1vjpf/72i2vfUgAIzYlCa71n7aCc21tx4EgBGb"
    "2Npcvz4TW10R+H7N9X+QhlItmusWXBW3DPs/AsCIHewbTD1hWHr6m2tvPQgAI7br7YHUE4Zl"
    "1/7+1BMajgAwYlt2H0o9YVi2NtneehAARmzj6z2pJwxZb/9gdO/xrULvJwCM2H/eOBC9A83x"
    "vnr9lv2+N+AYBIARG6wU8eimvalnDMlDG3enntCQBIBR+dvTb6ae8IH6DlcE4DgEgFF58pV9"
    "8dpbjX1y7a//frNp3qrUmwAwKtWiiF8/uDX1jOM6PFiN3z7cnXpGwxIARu3eDbti47YDqWcc"
    "092PboudTXa9Qj0JAKNWLYr40T2bYrDSWGfZu3cfijsa+NVJIxAAxsTLOw7GLX9/NfWMdx0e"
    "rMZ312yMgSOV1FMamgAwZtY8vi3WPbMz9YyIiPjxPS/Fph0HU89oeALAmCmKiB/+aVM8tmlP"
    "0h23/uPVWNsE/zzZCASAMXWkUo0bfv9C3P/8W3U/dlFE/GztK3HXw6/X/djNSgAYc++8/779"
    "gfqdgOvtH4zrf/dcrHlsW92OOR4IADVRLYr45f1b4urbn40d+2r7MdwnX90Xl9+yPh59Me1b"
    "j2bkJmnU1PrN++KLP38yvnT+3Lj8/FOjo23sfuW27+2L2+7dHP984a1ospsTNQwBoOb6j1Ti"
    "9ge2xh8e3x6XrDglLj6nK+acOGnEP29Dd0/88Yntcd/zuxru2oNmIwDUTU/fYPzmX91x18Pd"
    "sXhOZ3xy0YxYNn9aLOqaHB3tx/9V3HPgcLywrSfWb94fj7y4O96o8VuKnAgAdVcUERu3HXj3"
    "8uFSKWJ6x4SY2dkWnZMmRLmlFEcq1Xi7bzDe3N8fve7lVzMCQHJFEbH34JHYe/BI6inZ8a8A"
    "kDEBgIwJAGRMACBjAgAZEwDImABAxsb9dQADB3e+XVQrT6XekUpLtVwdzuMHenb2FsVgts/X"
    "0VqipXm++miExn0ADnQ/MzUilqfekUwlhnVPrJ7upztKpYyfr6MURXFf6g215i0AZEwAIGMC"
    "ABkTAMjYuD8JGEV0R1SeSD0jlaJcHtZJwJai2F5ENdvn62hFtLq7KAAAAAAAAADQNEqpB9Ta"
    "kuvXfrNUxJdT70ilGkXl+Zs++/GhPv7s69ZeERHfqOGk5lHEnRt+uuoXqWfU0vi/ErAac6NU"
    "yvbjrUWUhnUlYBGlrlLOH59+Lx8HBsYvAYCMCQBkTAAgYwIAGRMAyJgAQMYEADImAJAxAYCM"
    "CQBkTAAgYwIAGRMAyJgAQMYEADImAJAxAYCMCQBkTAAgYwIAGRMAyJgAQMYEADImAJAxAYCM"
    "CQBkTAAgYwIAGRMAyJgAQMYEADImAJAxAYCMCQBkTAAgYwIAGRMAyJgAQMYEADImAJAxAYCM"
    "CQBkTAAgYwIAGRMAyJgAQMYEADImAJAxAYCMCQBkTAAgYwIAGRMAyJgAQMYEADImAJAxAYCM"
    "taYeUGuVwd7+0mCpO/WOVIoiKsN5fHWgbyCq1Wyfr6NVy0V/6g21Nu4DsO+lR9ojYl7qHclU"
    "hheAPS8/1FYqZfx8HaUoivbUG2rNWwDImABAxgQAMiYAkLFxfxIwIg5VIvakHpFKuVwM6yRg"
    "FEVfpVTK9vk6WkupdCj1BgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAMjAfwFE6N1Ny8/f2gAAAABJRU5ErkJggg=="
    )

catalog["icon.ico"] = "icon_ico"
GetData_icon_ico   = icon_ico.GetData
GetImage_icon_ico  = icon_ico.GetImage
GetBitmap_icon_ico = icon_ico.GetBitmap
GetIcon_icon_ico   = icon_ico.GetIcon

